# Generated by Django 5.2.4 on 2025-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='empcity',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='empname',
            field=models.CharField(max_length=64),
        ),
    ]
