# Generated by Django 5.2.4 on 2025-10-14 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shifttask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftassignment',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
