# Generated by Django 5.2.4 on 2025-12-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='table',
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='restaurant.order'),
            preserve_default=False,
        ),
    ]
